db:
  image: postgres
  env_file: env/default
  ports:
    - "5432"

redis:
  image: redis
  ports:
    - "6379"

go-app:
  build: ./go-app
  env_file: env/default
  command: "gin -a 8080 r main.go"
  ports:
    - "3000:3000"
    - "8080:8080"
  volumes:
    - "./go-app:/go/src/github.com/mapzen/goexample"

python-app:
  build: ./python-app
  env_file: env/default
  links:
    - db
    - redis
  command: "gunicorn -b 0.0.0.0:8000 --reload sample:api"
  ports:
    - "8000:8000"
  volumes:
    - "./python-app:/app"
