db:
  env_file: env/default
  image: postgres
  ports:
    - "5432"

redis:
  env_file: env/default
  image: redis
  ports:
    - "6379"

go-app:
  env_file: env/default
  build: ./go-app
  command: "gin -a 8080 r main.go"
  ports:
    - "3000:3000"
    - "8080:8080"
  volumes:
    - "./go-app:/go/src/github.com/mapzen/goexample"

python-app:
  env_file: env/default
  build: ./python-app
  links:
    - db
    - redis
  command: "gunicorn -b 0.0.0.0:8000 --reload sample:api"
  ports:
    - "8000:8000"
  volumes:
    - "./python-app:/app"

nodejs-app:
  env_file: env/default
  build: ./nodejs-app
  command: "npm start"
  ports:
    - "4000:4000"
  volumes:
    - "./nodejs-app:/app"
    - "/app/node_modules"

ember-app:
  env_file: env/default
  build: ./ember-app
  env_file: env/default
  command: "server"
  ports:
    - "4200:4200"
  volumes:
    - "./ember-app:/app"

rails-app:
  env_file: env/default
  build: ./rails-app
  command: bundle exec rails s -p 3333 -b '0.0.0.0'
  volumes:
    - "./rails-app:/app"
  ports:
    - "3333:3333"
  links:
    - db
    - redis

spark-app:
  env_file: env/default
  build: ./spark-app
  volumes:
    - "./spark-app:/app"
  ports:
    - "4567:4567"
  links:
    - db
    - redis
