go-app:
  build: ./go-app
  env_file: env/default
  command: "gin -a 8080 r main.go"
  #links:
  #  - db
  #  - redis
  ports:
    - "3000:3000"
    - "8080:8080"
  volumes:
    - "./go-app:/go/src/github.com/mapzen/goexample"
